// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: saicdatamodel.proto

package com.saic.bigdata;

public final class SaicDataModel {
  /*private SaicDataModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Rx5DataModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Rx5DataModel)
      com.google.protobuf.MessageOrBuilder {

    *//**
     * <code>optional string pk = 1;</code>
     *//*
    java.lang.String getPk();
    *//**
     * <code>optional string pk = 1;</code>
     *//*
    com.google.protobuf.ByteString
        getPkBytes();

    *//**
     * <code>optional string vin = 2;</code>
     *//*
    java.lang.String getVin();
    *//**
     * <code>optional string vin = 2;</code>
     *//*
    com.google.protobuf.ByteString
        getVinBytes();

    *//**
     * <code>optional string work_model = 3;</code>
     *//*
    java.lang.String getWorkModel();
    *//**
     * <code>optional string work_model = 3;</code>
     *//*
    com.google.protobuf.ByteString
        getWorkModelBytes();

    *//**
     * <code>optional string hevsystemmode = 4;</code>
     *//*
    java.lang.String getHevsystemmode();
    *//**
     * <code>optional string hevsystemmode = 4;</code>
     *//*
    com.google.protobuf.ByteString
        getHevsystemmodeBytes();

    *//**
     * <code>optional string data_date = 5;</code>
     *//*
    java.lang.String getDataDate();
    *//**
     * <code>optional string data_date = 5;</code>
     *//*
    com.google.protobuf.ByteString
        getDataDateBytes();

    *//**
     * <code>optional string latitude = 6;</code>
     *//*
    java.lang.String getLatitude();
    *//**
     * <code>optional string latitude = 6;</code>
     *//*
    com.google.protobuf.ByteString
        getLatitudeBytes();

    *//**
     * <code>optional string longitude = 7;</code>
     *//*
    java.lang.String getLongitude();
    *//**
     * <code>optional string longitude = 7;</code>
     *//*
    com.google.protobuf.ByteString
        getLongitudeBytes();
  }
  *//**
   * Protobuf type {@code tutorial.Rx5DataModel}
   *//*
  public  static final class Rx5DataModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Rx5DataModel)
      Rx5DataModelOrBuilder {
    // Use Rx5DataModel.newBuilder() to construct.
    private Rx5DataModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Rx5DataModel() {
      pk_ = "";
      vin_ = "";
      workModel_ = "";
      hevsystemmode_ = "";
      dataDate_ = "";
      latitude_ = "";
      longitude_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Rx5DataModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              pk_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              vin_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              workModel_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              hevsystemmode_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              dataDate_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              latitude_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              longitude_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.saic.bigdata.SaicDataModel.internal_static_tutorial_Rx5DataModel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.saic.bigdata.SaicDataModel.internal_static_tutorial_Rx5DataModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.saic.bigdata.SaicDataModel.Rx5DataModel.class, com.saic.bigdata.SaicDataModel.Rx5DataModel.Builder.class);
    }

    public static final int PK_FIELD_NUMBER = 1;
    private volatile java.lang.Object pk_;
    *//**
     * <code>optional string pk = 1;</code>
     *//*
    public java.lang.String getPk() {
      java.lang.Object ref = pk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pk_ = s;
        return s;
      }
    }
    *//**
     * <code>optional string pk = 1;</code>
     *//*
    public com.google.protobuf.ByteString
        getPkBytes() {
      java.lang.Object ref = pk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VIN_FIELD_NUMBER = 2;
    private volatile java.lang.Object vin_;
    *//**
     * <code>optional string vin = 2;</code>
     *//*
    public java.lang.String getVin() {
      java.lang.Object ref = vin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vin_ = s;
        return s;
      }
    }
    *//**
     * <code>optional string vin = 2;</code>
     *//*
    public com.google.protobuf.ByteString
        getVinBytes() {
      java.lang.Object ref = vin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WORK_MODEL_FIELD_NUMBER = 3;
    private volatile java.lang.Object workModel_;
    *//**
     * <code>optional string work_model = 3;</code>
     *//*
    public java.lang.String getWorkModel() {
      java.lang.Object ref = workModel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workModel_ = s;
        return s;
      }
    }
    *//**
     * <code>optional string work_model = 3;</code>
     *//*
    public com.google.protobuf.ByteString
        getWorkModelBytes() {
      java.lang.Object ref = workModel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEVSYSTEMMODE_FIELD_NUMBER = 4;
    private volatile java.lang.Object hevsystemmode_;
    *//**
     * <code>optional string hevsystemmode = 4;</code>
     *//*
    public java.lang.String getHevsystemmode() {
      java.lang.Object ref = hevsystemmode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hevsystemmode_ = s;
        return s;
      }
    }
    *//**
     * <code>optional string hevsystemmode = 4;</code>
     *//*
    public com.google.protobuf.ByteString
        getHevsystemmodeBytes() {
      java.lang.Object ref = hevsystemmode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hevsystemmode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_DATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object dataDate_;
    *//**
     * <code>optional string data_date = 5;</code>
     *//*
    public java.lang.String getDataDate() {
      java.lang.Object ref = dataDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataDate_ = s;
        return s;
      }
    }
    *//**
     * <code>optional string data_date = 5;</code>
     *//*
    public com.google.protobuf.ByteString
        getDataDateBytes() {
      java.lang.Object ref = dataDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDE_FIELD_NUMBER = 6;
    private volatile java.lang.Object latitude_;
    *//**
     * <code>optional string latitude = 6;</code>
     *//*
    public java.lang.String getLatitude() {
      java.lang.Object ref = latitude_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        latitude_ = s;
        return s;
      }
    }
    *//**
     * <code>optional string latitude = 6;</code>
     *//*
    public com.google.protobuf.ByteString
        getLatitudeBytes() {
      java.lang.Object ref = latitude_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        latitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LONGITUDE_FIELD_NUMBER = 7;
    private volatile java.lang.Object longitude_;
    *//**
     * <code>optional string longitude = 7;</code>
     *//*
    public java.lang.String getLongitude() {
      java.lang.Object ref = longitude_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        longitude_ = s;
        return s;
      }
    }
    *//**
     * <code>optional string longitude = 7;</code>
     *//*
    public com.google.protobuf.ByteString
        getLongitudeBytes() {
      java.lang.Object ref = longitude_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        longitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pk_);
      }
      if (!getVinBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, vin_);
      }
      if (!getWorkModelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, workModel_);
      }
      if (!getHevsystemmodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, hevsystemmode_);
      }
      if (!getDataDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dataDate_);
      }
      if (!getLatitudeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, latitude_);
      }
      if (!getLongitudeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, longitude_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pk_);
      }
      if (!getVinBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, vin_);
      }
      if (!getWorkModelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, workModel_);
      }
      if (!getHevsystemmodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, hevsystemmode_);
      }
      if (!getDataDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dataDate_);
      }
      if (!getLatitudeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, latitude_);
      }
      if (!getLongitudeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, longitude_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.saic.bigdata.SaicDataModel.Rx5DataModel)) {
        return super.equals(obj);
      }
      com.saic.bigdata.SaicDataModel.Rx5DataModel other = (com.saic.bigdata.SaicDataModel.Rx5DataModel) obj;

      boolean result = true;
      result = result && getPk()
          .equals(other.getPk());
      result = result && getVin()
          .equals(other.getVin());
      result = result && getWorkModel()
          .equals(other.getWorkModel());
      result = result && getHevsystemmode()
          .equals(other.getHevsystemmode());
      result = result && getDataDate()
          .equals(other.getDataDate());
      result = result && getLatitude()
          .equals(other.getLatitude());
      result = result && getLongitude()
          .equals(other.getLongitude());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PK_FIELD_NUMBER;
      hash = (53 * hash) + getPk().hashCode();
      hash = (37 * hash) + VIN_FIELD_NUMBER;
      hash = (53 * hash) + getVin().hashCode();
      hash = (37 * hash) + WORK_MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getWorkModel().hashCode();
      hash = (37 * hash) + HEVSYSTEMMODE_FIELD_NUMBER;
      hash = (53 * hash) + getHevsystemmode().hashCode();
      hash = (37 * hash) + DATA_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDataDate().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLatitude().hashCode();
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLongitude().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.saic.bigdata.SaicDataModel.Rx5DataModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.saic.bigdata.SaicDataModel.Rx5DataModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    *//**
     * Protobuf type {@code tutorial.Rx5DataModel}
     *//*
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Rx5DataModel)
        com.saic.bigdata.SaicDataModel.Rx5DataModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.saic.bigdata.SaicDataModel.internal_static_tutorial_Rx5DataModel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.saic.bigdata.SaicDataModel.internal_static_tutorial_Rx5DataModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.saic.bigdata.SaicDataModel.Rx5DataModel.class, com.saic.bigdata.SaicDataModel.Rx5DataModel.Builder.class);
      }

      // Construct using com.saic.bigdata.SaicDataModel.Rx5DataModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pk_ = "";

        vin_ = "";

        workModel_ = "";

        hevsystemmode_ = "";

        dataDate_ = "";

        latitude_ = "";

        longitude_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.saic.bigdata.SaicDataModel.internal_static_tutorial_Rx5DataModel_descriptor;
      }

      public com.saic.bigdata.SaicDataModel.Rx5DataModel getDefaultInstanceForType() {
        return com.saic.bigdata.SaicDataModel.Rx5DataModel.getDefaultInstance();
      }

      public com.saic.bigdata.SaicDataModel.Rx5DataModel build() {
        com.saic.bigdata.SaicDataModel.Rx5DataModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.saic.bigdata.SaicDataModel.Rx5DataModel buildPartial() {
        com.saic.bigdata.SaicDataModel.Rx5DataModel result = new com.saic.bigdata.SaicDataModel.Rx5DataModel(this);
        result.pk_ = pk_;
        result.vin_ = vin_;
        result.workModel_ = workModel_;
        result.hevsystemmode_ = hevsystemmode_;
        result.dataDate_ = dataDate_;
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.saic.bigdata.SaicDataModel.Rx5DataModel) {
          return mergeFrom((com.saic.bigdata.SaicDataModel.Rx5DataModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.saic.bigdata.SaicDataModel.Rx5DataModel other) {
        if (other == com.saic.bigdata.SaicDataModel.Rx5DataModel.getDefaultInstance()) return this;
        if (!other.getPk().isEmpty()) {
          pk_ = other.pk_;
          onChanged();
        }
        if (!other.getVin().isEmpty()) {
          vin_ = other.vin_;
          onChanged();
        }
        if (!other.getWorkModel().isEmpty()) {
          workModel_ = other.workModel_;
          onChanged();
        }
        if (!other.getHevsystemmode().isEmpty()) {
          hevsystemmode_ = other.hevsystemmode_;
          onChanged();
        }
        if (!other.getDataDate().isEmpty()) {
          dataDate_ = other.dataDate_;
          onChanged();
        }
        if (!other.getLatitude().isEmpty()) {
          latitude_ = other.latitude_;
          onChanged();
        }
        if (!other.getLongitude().isEmpty()) {
          longitude_ = other.longitude_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.saic.bigdata.SaicDataModel.Rx5DataModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.saic.bigdata.SaicDataModel.Rx5DataModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object pk_ = "";
      *//**
       * <code>optional string pk = 1;</code>
       *//*
      public java.lang.String getPk() {
        java.lang.Object ref = pk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      *//**
       * <code>optional string pk = 1;</code>
       *//*
      public com.google.protobuf.ByteString
          getPkBytes() {
        java.lang.Object ref = pk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      *//**
       * <code>optional string pk = 1;</code>
       *//*
      public Builder setPk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pk_ = value;
        onChanged();
        return this;
      }
      *//**
       * <code>optional string pk = 1;</code>
       *//*
      public Builder clearPk() {
        
        pk_ = getDefaultInstance().getPk();
        onChanged();
        return this;
      }
      *//**
       * <code>optional string pk = 1;</code>
       *//*
      public Builder setPkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pk_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object vin_ = "";
      *//**
       * <code>optional string vin = 2;</code>
       *//*
      public java.lang.String getVin() {
        java.lang.Object ref = vin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      *//**
       * <code>optional string vin = 2;</code>
       *//*
      public com.google.protobuf.ByteString
          getVinBytes() {
        java.lang.Object ref = vin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      *//**
       * <code>optional string vin = 2;</code>
       *//*
      public Builder setVin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vin_ = value;
        onChanged();
        return this;
      }
      *//**
       * <code>optional string vin = 2;</code>
       *//*
      public Builder clearVin() {
        
        vin_ = getDefaultInstance().getVin();
        onChanged();
        return this;
      }
      *//**
       * <code>optional string vin = 2;</code>
       *//*
      public Builder setVinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        vin_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object workModel_ = "";
      *//**
       * <code>optional string work_model = 3;</code>
       *//*
      public java.lang.String getWorkModel() {
        java.lang.Object ref = workModel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workModel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      *//**
       * <code>optional string work_model = 3;</code>
       *//*
      public com.google.protobuf.ByteString
          getWorkModelBytes() {
        java.lang.Object ref = workModel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workModel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      *//**
       * <code>optional string work_model = 3;</code>
       *//*
      public Builder setWorkModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workModel_ = value;
        onChanged();
        return this;
      }
      *//**
       * <code>optional string work_model = 3;</code>
       *//*
      public Builder clearWorkModel() {
        
        workModel_ = getDefaultInstance().getWorkModel();
        onChanged();
        return this;
      }
      *//**
       * <code>optional string work_model = 3;</code>
       *//*
      public Builder setWorkModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workModel_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hevsystemmode_ = "";
      *//**
       * <code>optional string hevsystemmode = 4;</code>
       *//*
      public java.lang.String getHevsystemmode() {
        java.lang.Object ref = hevsystemmode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hevsystemmode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      *//**
       * <code>optional string hevsystemmode = 4;</code>
       *//*
      public com.google.protobuf.ByteString
          getHevsystemmodeBytes() {
        java.lang.Object ref = hevsystemmode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hevsystemmode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      *//**
       * <code>optional string hevsystemmode = 4;</code>
       *//*
      public Builder setHevsystemmode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hevsystemmode_ = value;
        onChanged();
        return this;
      }
      *//**
       * <code>optional string hevsystemmode = 4;</code>
       *//*
      public Builder clearHevsystemmode() {
        
        hevsystemmode_ = getDefaultInstance().getHevsystemmode();
        onChanged();
        return this;
      }
      *//**
       * <code>optional string hevsystemmode = 4;</code>
       *//*
      public Builder setHevsystemmodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hevsystemmode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataDate_ = "";
      *//**
       * <code>optional string data_date = 5;</code>
       *//*
      public java.lang.String getDataDate() {
        java.lang.Object ref = dataDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      *//**
       * <code>optional string data_date = 5;</code>
       *//*
      public com.google.protobuf.ByteString
          getDataDateBytes() {
        java.lang.Object ref = dataDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      *//**
       * <code>optional string data_date = 5;</code>
       *//*
      public Builder setDataDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataDate_ = value;
        onChanged();
        return this;
      }
      *//**
       * <code>optional string data_date = 5;</code>
       *//*
      public Builder clearDataDate() {
        
        dataDate_ = getDefaultInstance().getDataDate();
        onChanged();
        return this;
      }
      *//**
       * <code>optional string data_date = 5;</code>
       *//*
      public Builder setDataDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object latitude_ = "";
      *//**
       * <code>optional string latitude = 6;</code>
       *//*
      public java.lang.String getLatitude() {
        java.lang.Object ref = latitude_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          latitude_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      *//**
       * <code>optional string latitude = 6;</code>
       *//*
      public com.google.protobuf.ByteString
          getLatitudeBytes() {
        java.lang.Object ref = latitude_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          latitude_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      *//**
       * <code>optional string latitude = 6;</code>
       *//*
      public Builder setLatitude(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        latitude_ = value;
        onChanged();
        return this;
      }
      *//**
       * <code>optional string latitude = 6;</code>
       *//*
      public Builder clearLatitude() {
        
        latitude_ = getDefaultInstance().getLatitude();
        onChanged();
        return this;
      }
      *//**
       * <code>optional string latitude = 6;</code>
       *//*
      public Builder setLatitudeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        latitude_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object longitude_ = "";
      *//**
       * <code>optional string longitude = 7;</code>
       *//*
      public java.lang.String getLongitude() {
        java.lang.Object ref = longitude_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          longitude_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      *//**
       * <code>optional string longitude = 7;</code>
       *//*
      public com.google.protobuf.ByteString
          getLongitudeBytes() {
        java.lang.Object ref = longitude_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          longitude_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      *//**
       * <code>optional string longitude = 7;</code>
       *//*
      public Builder setLongitude(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        longitude_ = value;
        onChanged();
        return this;
      }
      *//**
       * <code>optional string longitude = 7;</code>
       *//*
      public Builder clearLongitude() {
        
        longitude_ = getDefaultInstance().getLongitude();
        onChanged();
        return this;
      }
      *//**
       * <code>optional string longitude = 7;</code>
       *//*
      public Builder setLongitudeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        longitude_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Rx5DataModel)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Rx5DataModel)
    private static final com.saic.bigdata.SaicDataModel.Rx5DataModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.saic.bigdata.SaicDataModel.Rx5DataModel();
    }

    public static com.saic.bigdata.SaicDataModel.Rx5DataModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Rx5DataModel>
        PARSER = new com.google.protobuf.AbstractParser<Rx5DataModel>() {
      public Rx5DataModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Rx5DataModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Rx5DataModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Rx5DataModel> getParserForType() {
      return PARSER;
    }

    public com.saic.bigdata.SaicDataModel.Rx5DataModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Rx5DataModelListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Rx5DataModelList)
      com.google.protobuf.MessageOrBuilder {

    *//**
     * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
     *//*
    java.util.List<com.saic.bigdata.SaicDataModel.Rx5DataModel> 
        getDataModelList();
    *//**
     * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
     *//*
    com.saic.bigdata.SaicDataModel.Rx5DataModel getDataModel(int index);
    *//**
     * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
     *//*
    int getDataModelCount();
    *//**
     * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
     *//*
    java.util.List<? extends com.saic.bigdata.SaicDataModel.Rx5DataModelOrBuilder> 
        getDataModelOrBuilderList();
    *//**
     * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
     *//*
    com.saic.bigdata.SaicDataModel.Rx5DataModelOrBuilder getDataModelOrBuilder(
        int index);
  }
  *//**
   * Protobuf type {@code tutorial.Rx5DataModelList}
   *//*
  public  static final class Rx5DataModelList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Rx5DataModelList)
      Rx5DataModelListOrBuilder {
    // Use Rx5DataModelList.newBuilder() to construct.
    private Rx5DataModelList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Rx5DataModelList() {
      dataModel_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Rx5DataModelList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                dataModel_ = new java.util.ArrayList<com.saic.bigdata.SaicDataModel.Rx5DataModel>();
                mutable_bitField0_ |= 0x00000001;
              }
              dataModel_.add(
                  input.readMessage(com.saic.bigdata.SaicDataModel.Rx5DataModel.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          dataModel_ = java.util.Collections.unmodifiableList(dataModel_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.saic.bigdata.SaicDataModel.internal_static_tutorial_Rx5DataModelList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.saic.bigdata.SaicDataModel.internal_static_tutorial_Rx5DataModelList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.saic.bigdata.SaicDataModel.Rx5DataModelList.class, com.saic.bigdata.SaicDataModel.Rx5DataModelList.Builder.class);
    }

    public static final int DATAMODEL_FIELD_NUMBER = 1;
    private java.util.List<com.saic.bigdata.SaicDataModel.Rx5DataModel> dataModel_;
    *//**
     * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
     *//*
    public java.util.List<com.saic.bigdata.SaicDataModel.Rx5DataModel> getDataModelList() {
      return dataModel_;
    }
    *//**
     * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
     *//*
    public java.util.List<? extends com.saic.bigdata.SaicDataModel.Rx5DataModelOrBuilder> 
        getDataModelOrBuilderList() {
      return dataModel_;
    }
    *//**
     * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
     *//*
    public int getDataModelCount() {
      return dataModel_.size();
    }
    *//**
     * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
     *//*
    public com.saic.bigdata.SaicDataModel.Rx5DataModel getDataModel(int index) {
      return dataModel_.get(index);
    }
    *//**
     * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
     *//*
    public com.saic.bigdata.SaicDataModel.Rx5DataModelOrBuilder getDataModelOrBuilder(
        int index) {
      return dataModel_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < dataModel_.size(); i++) {
        output.writeMessage(1, dataModel_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dataModel_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dataModel_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.saic.bigdata.SaicDataModel.Rx5DataModelList)) {
        return super.equals(obj);
      }
      com.saic.bigdata.SaicDataModel.Rx5DataModelList other = (com.saic.bigdata.SaicDataModel.Rx5DataModelList) obj;

      boolean result = true;
      result = result && getDataModelList()
          .equals(other.getDataModelList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getDataModelCount() > 0) {
        hash = (37 * hash) + DATAMODEL_FIELD_NUMBER;
        hash = (53 * hash) + getDataModelList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.saic.bigdata.SaicDataModel.Rx5DataModelList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModelList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModelList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModelList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModelList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModelList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModelList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModelList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModelList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.saic.bigdata.SaicDataModel.Rx5DataModelList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.saic.bigdata.SaicDataModel.Rx5DataModelList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    *//**
     * Protobuf type {@code tutorial.Rx5DataModelList}
     *//*
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Rx5DataModelList)
        com.saic.bigdata.SaicDataModel.Rx5DataModelListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.saic.bigdata.SaicDataModel.internal_static_tutorial_Rx5DataModelList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.saic.bigdata.SaicDataModel.internal_static_tutorial_Rx5DataModelList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.saic.bigdata.SaicDataModel.Rx5DataModelList.class, com.saic.bigdata.SaicDataModel.Rx5DataModelList.Builder.class);
      }

      // Construct using com.saic.bigdata.SaicDataModel.Rx5DataModelList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataModelFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (dataModelBuilder_ == null) {
          dataModel_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataModelBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.saic.bigdata.SaicDataModel.internal_static_tutorial_Rx5DataModelList_descriptor;
      }

      public com.saic.bigdata.SaicDataModel.Rx5DataModelList getDefaultInstanceForType() {
        return com.saic.bigdata.SaicDataModel.Rx5DataModelList.getDefaultInstance();
      }

      public com.saic.bigdata.SaicDataModel.Rx5DataModelList build() {
        com.saic.bigdata.SaicDataModel.Rx5DataModelList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.saic.bigdata.SaicDataModel.Rx5DataModelList buildPartial() {
        com.saic.bigdata.SaicDataModel.Rx5DataModelList result = new com.saic.bigdata.SaicDataModel.Rx5DataModelList(this);
        int from_bitField0_ = bitField0_;
        if (dataModelBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            dataModel_ = java.util.Collections.unmodifiableList(dataModel_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dataModel_ = dataModel_;
        } else {
          result.dataModel_ = dataModelBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.saic.bigdata.SaicDataModel.Rx5DataModelList) {
          return mergeFrom((com.saic.bigdata.SaicDataModel.Rx5DataModelList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.saic.bigdata.SaicDataModel.Rx5DataModelList other) {
        if (other == com.saic.bigdata.SaicDataModel.Rx5DataModelList.getDefaultInstance()) return this;
        if (dataModelBuilder_ == null) {
          if (!other.dataModel_.isEmpty()) {
            if (dataModel_.isEmpty()) {
              dataModel_ = other.dataModel_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataModelIsMutable();
              dataModel_.addAll(other.dataModel_);
            }
            onChanged();
          }
        } else {
          if (!other.dataModel_.isEmpty()) {
            if (dataModelBuilder_.isEmpty()) {
              dataModelBuilder_.dispose();
              dataModelBuilder_ = null;
              dataModel_ = other.dataModel_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataModelBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataModelFieldBuilder() : null;
            } else {
              dataModelBuilder_.addAllMessages(other.dataModel_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.saic.bigdata.SaicDataModel.Rx5DataModelList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.saic.bigdata.SaicDataModel.Rx5DataModelList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.saic.bigdata.SaicDataModel.Rx5DataModel> dataModel_ =
        java.util.Collections.emptyList();
      private void ensureDataModelIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          dataModel_ = new java.util.ArrayList<com.saic.bigdata.SaicDataModel.Rx5DataModel>(dataModel_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.saic.bigdata.SaicDataModel.Rx5DataModel, com.saic.bigdata.SaicDataModel.Rx5DataModel.Builder, com.saic.bigdata.SaicDataModel.Rx5DataModelOrBuilder> dataModelBuilder_;

      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public java.util.List<com.saic.bigdata.SaicDataModel.Rx5DataModel> getDataModelList() {
        if (dataModelBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dataModel_);
        } else {
          return dataModelBuilder_.getMessageList();
        }
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public int getDataModelCount() {
        if (dataModelBuilder_ == null) {
          return dataModel_.size();
        } else {
          return dataModelBuilder_.getCount();
        }
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public com.saic.bigdata.SaicDataModel.Rx5DataModel getDataModel(int index) {
        if (dataModelBuilder_ == null) {
          return dataModel_.get(index);
        } else {
          return dataModelBuilder_.getMessage(index);
        }
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public Builder setDataModel(
          int index, com.saic.bigdata.SaicDataModel.Rx5DataModel value) {
        if (dataModelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataModelIsMutable();
          dataModel_.set(index, value);
          onChanged();
        } else {
          dataModelBuilder_.setMessage(index, value);
        }
        return this;
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public Builder setDataModel(
          int index, com.saic.bigdata.SaicDataModel.Rx5DataModel.Builder builderForValue) {
        if (dataModelBuilder_ == null) {
          ensureDataModelIsMutable();
          dataModel_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataModelBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public Builder addDataModel(com.saic.bigdata.SaicDataModel.Rx5DataModel value) {
        if (dataModelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataModelIsMutable();
          dataModel_.add(value);
          onChanged();
        } else {
          dataModelBuilder_.addMessage(value);
        }
        return this;
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public Builder addDataModel(
          int index, com.saic.bigdata.SaicDataModel.Rx5DataModel value) {
        if (dataModelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataModelIsMutable();
          dataModel_.add(index, value);
          onChanged();
        } else {
          dataModelBuilder_.addMessage(index, value);
        }
        return this;
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public Builder addDataModel(
          com.saic.bigdata.SaicDataModel.Rx5DataModel.Builder builderForValue) {
        if (dataModelBuilder_ == null) {
          ensureDataModelIsMutable();
          dataModel_.add(builderForValue.build());
          onChanged();
        } else {
          dataModelBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public Builder addDataModel(
          int index, com.saic.bigdata.SaicDataModel.Rx5DataModel.Builder builderForValue) {
        if (dataModelBuilder_ == null) {
          ensureDataModelIsMutable();
          dataModel_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataModelBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public Builder addAllDataModel(
          java.lang.Iterable<? extends com.saic.bigdata.SaicDataModel.Rx5DataModel> values) {
        if (dataModelBuilder_ == null) {
          ensureDataModelIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dataModel_);
          onChanged();
        } else {
          dataModelBuilder_.addAllMessages(values);
        }
        return this;
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public Builder clearDataModel() {
        if (dataModelBuilder_ == null) {
          dataModel_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataModelBuilder_.clear();
        }
        return this;
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public Builder removeDataModel(int index) {
        if (dataModelBuilder_ == null) {
          ensureDataModelIsMutable();
          dataModel_.remove(index);
          onChanged();
        } else {
          dataModelBuilder_.remove(index);
        }
        return this;
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public com.saic.bigdata.SaicDataModel.Rx5DataModel.Builder getDataModelBuilder(
          int index) {
        return getDataModelFieldBuilder().getBuilder(index);
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public com.saic.bigdata.SaicDataModel.Rx5DataModelOrBuilder getDataModelOrBuilder(
          int index) {
        if (dataModelBuilder_ == null) {
          return dataModel_.get(index);  } else {
          return dataModelBuilder_.getMessageOrBuilder(index);
        }
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public java.util.List<? extends com.saic.bigdata.SaicDataModel.Rx5DataModelOrBuilder> 
           getDataModelOrBuilderList() {
        if (dataModelBuilder_ != null) {
          return dataModelBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dataModel_);
        }
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public com.saic.bigdata.SaicDataModel.Rx5DataModel.Builder addDataModelBuilder() {
        return getDataModelFieldBuilder().addBuilder(
            com.saic.bigdata.SaicDataModel.Rx5DataModel.getDefaultInstance());
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public com.saic.bigdata.SaicDataModel.Rx5DataModel.Builder addDataModelBuilder(
          int index) {
        return getDataModelFieldBuilder().addBuilder(
            index, com.saic.bigdata.SaicDataModel.Rx5DataModel.getDefaultInstance());
      }
      *//**
       * <code>repeated .tutorial.Rx5DataModel dataModel = 1;</code>
       *//*
      public java.util.List<com.saic.bigdata.SaicDataModel.Rx5DataModel.Builder> 
           getDataModelBuilderList() {
        return getDataModelFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.saic.bigdata.SaicDataModel.Rx5DataModel, com.saic.bigdata.SaicDataModel.Rx5DataModel.Builder, com.saic.bigdata.SaicDataModel.Rx5DataModelOrBuilder> 
          getDataModelFieldBuilder() {
        if (dataModelBuilder_ == null) {
          dataModelBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.saic.bigdata.SaicDataModel.Rx5DataModel, com.saic.bigdata.SaicDataModel.Rx5DataModel.Builder, com.saic.bigdata.SaicDataModel.Rx5DataModelOrBuilder>(
                  dataModel_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          dataModel_ = null;
        }
        return dataModelBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Rx5DataModelList)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Rx5DataModelList)
    private static final com.saic.bigdata.SaicDataModel.Rx5DataModelList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.saic.bigdata.SaicDataModel.Rx5DataModelList();
    }

    public static com.saic.bigdata.SaicDataModel.Rx5DataModelList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Rx5DataModelList>
        PARSER = new com.google.protobuf.AbstractParser<Rx5DataModelList>() {
      public Rx5DataModelList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Rx5DataModelList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Rx5DataModelList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Rx5DataModelList> getParserForType() {
      return PARSER;
    }

    public com.saic.bigdata.SaicDataModel.Rx5DataModelList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Rx5DataModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Rx5DataModel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Rx5DataModelList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Rx5DataModelList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023saicdatamodel.proto\022\010tutorial\"\212\001\n\014Rx5D" +
      "ataModel\022\n\n\002pk\030\001 \001(\t\022\013\n\003vin\030\002 \001(\t\022\022\n\nwor" +
      "k_model\030\003 \001(\t\022\025\n\rhevsystemmode\030\004 \001(\t\022\021\n\t" +
      "data_date\030\005 \001(\t\022\020\n\010latitude\030\006 \001(\t\022\021\n\tlon" +
      "gitude\030\007 \001(\t\"=\n\020Rx5DataModelList\022)\n\tdata" +
      "Model\030\001 \003(\0132\026.tutorial.Rx5DataModelB!\n\020c" +
      "om.saic.bigdataB\rSaicDataModelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_Rx5DataModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Rx5DataModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Rx5DataModel_descriptor,
        new java.lang.String[] { "Pk", "Vin", "WorkModel", "Hevsystemmode", "DataDate", "Latitude", "Longitude", });
    internal_static_tutorial_Rx5DataModelList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_Rx5DataModelList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Rx5DataModelList_descriptor,
        new java.lang.String[] { "DataModel", });
  }*/

  // @@protoc_insertion_point(outer_class_scope)
}
